samples:
    - ggF
    # - VBF
    # - WH
    # - ZH
    # - ttH
    # - WJetsLNu
    # - TTbar
    # - SingleTop
    # - Diboson
    # - EWKvjets
    # - DYJets
    # - WZQQ
    # - Data

regions_sel:

    # "VBF": (n_bjets_T==0) & (THWW>0.905) & ( (mjj>1000) & (deta>3.5) ) & (rec_higgs_pt>250)
    "ggFpt250to350": (n_bjets_T==0) & (THWW>0.93) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggFpt350to500": (n_bjets_T==0) & (THWW>0.93) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    # "ggFpt500toInf": (n_bjets_T==0) & (THWW>0.93) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "WJetsCR": (n_bjets_T==0) & (THWW<0.905) & (rec_higgs_pt>250)
    # "TopCR": (n_bjets_T>0) & (rec_higgs_pt>250)

samples_dir:
    "2018": ../eos/July18_hww_2018
    "2017": ../eos/July18_hww_2017
    "2016": ../eos/July18_hww_2016
    "2016APV": ../eos/July18_hww_2016APV

model_path: ../../weaver-core-dev/experiments_finetuning/v35_30/model.onnx
