samples:
    - ggF
    - VBF
    - ttH
    - WH
    - ZH
    - WJetsLNu
    - TTbar
    - SingleTop
    - Diboson
    - EWKvjets
    - DYJets
    - WZQQ
    - Data

regions_sel:
    "WJetsCR": (THWW>0.50) & (THWW<0.88) & (n_bjets_T==0)
    "TopCR": (THWW>0.50) & (n_bjets_T>0)

    ### ParT vs ParT-Finetuned (no VBF and ggF categorization)
    "ParT9999": (fj_ParT_score>0.9999) & (n_bjets_T==0)
    "ParT9995": (fj_ParT_score>0.9995) & (n_bjets_T==0)
    "ParT999": (fj_ParT_score>0.999) & (n_bjets_T==0)
    "ParT995": (fj_ParT_score>0.995) & (n_bjets_T==0)
    "ParT99": (fj_ParT_score>0.99) & (n_bjets_T==0)
    "ParT985": (fj_ParT_score>0.985) & (n_bjets_T==0)
    "ParT98": (fj_ParT_score>0.98) & (n_bjets_T==0)
    "ParT975": (fj_ParT_score>0.975) & (n_bjets_T==0)
    "ParT97": (fj_ParT_score>0.97) & (n_bjets_T==0)
    "ParT965": (fj_ParT_score>0.965) & (n_bjets_T==0)
    "ParT96": (fj_ParT_score>0.96) & (n_bjets_T==0)
    "ParT955": (fj_ParT_score>0.955) & (n_bjets_T==0)
    "ParT95": (fj_ParT_score>0.95) & (n_bjets_T==0)
    "ParT945": (fj_ParT_score>0.945) & (n_bjets_T==0)
    "ParT94": (fj_ParT_score>0.94) & (n_bjets_T==0)

    "THWW999": (THWW>0.999) & (n_bjets_T==0)
    "THWW995": (THWW>0.995) & (n_bjets_T==0)
    "THWW99": (THWW>0.99) & (n_bjets_T==0)
    "THWW985": (THWW>0.985) & (n_bjets_T==0)
    "THWW98": (THWW>0.98) & (n_bjets_T==0)
    "THWW975": (THWW>0.975) & (n_bjets_T==0)
    "THWW97": (THWW>0.97) & (n_bjets_T==0)
    "THWW965": (THWW>0.965) & (n_bjets_T==0)
    "THWW96": (THWW>0.96) & (n_bjets_T==0)
    "THWW955": (THWW>0.955) & (n_bjets_T==0)
    "THWW95": (THWW>0.95) & (n_bjets_T==0)
    "THWW945": (THWW>0.945) & (n_bjets_T==0)
    "THWW94": (THWW>0.94) & (n_bjets_T==0)
    "THWW935": (THWW>0.935) & (n_bjets_T==0)
    "THWW93": (THWW>0.93) & (n_bjets_T==0)
    "THWW925": (THWW>0.925) & (n_bjets_T==0)
    "THWW92": (THWW>0.92) & (n_bjets_T==0)

    ### ggF all inclusive
    "ggF95": (THWW>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF945": (THWW>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF94": (THWW>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF935": (THWW>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF93": (THWW>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF925": (THWW>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF92": (THWW>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF915": (THWW>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF91": (THWW>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF905": (THWW>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF90": (THWW>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF895": (THWW>0.895) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF89": (THWW>0.89) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF885": (THWW>0.885) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )
    "ggF88": (THWW>0.88) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) )

    ### VBF all inclusive
    "VBF92": (THWW>0.92) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF915": (THWW>0.915) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF91": (THWW>0.91) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF905": (THWW>0.905) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF90": (THWW>0.90) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF895": (THWW>0.895) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF89": (THWW>0.89) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF885": (THWW>885) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )
    "VBF88": (THWW>88) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) )

    ### ggF pt bins
    "ggF95pt250to300": (THWW>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF95pt300to450": (THWW>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF95pt450toInf": (THWW>0.95) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF945pt250to300": (THWW>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF945pt300to450": (THWW>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF945pt450toInf": (THWW>0.945) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF94pt250to300": (THWW>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF94pt300to450": (THWW>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF94pt450toInf": (THWW>0.94) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF935pt250to300": (THWW>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF935pt300to450": (THWW>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF935pt450toInf": (THWW>0.935) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF93pt250to300": (THWW>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF93pt300to450": (THWW>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF93pt450toInf": (THWW>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF925pt250to300": (THWW>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF925pt300to450": (THWW>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF925pt450toInf": (THWW>0.925) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF92pt250to300": (THWW>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF92pt300to450": (THWW>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF92pt450toInf": (THWW>0.92) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF915pt250to300": (THWW>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF915pt300to450": (THWW>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF915pt450toInf": (THWW>0.915) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF91pt250to300": (THWW>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF91pt300to450": (THWW>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF91pt450toInf": (THWW>0.91) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF905pt250to300": (THWW>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF905pt300to450": (THWW>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF905pt450toInf": (THWW>0.905) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF90pt250to300": (THWW>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF90pt300to450": (THWW>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF90pt450toInf": (THWW>0.90) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF895pt250to300": (THWW>0.895) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF895pt300to450": (THWW>0.895) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF895pt450toInf": (THWW>0.895) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF89pt250to300": (THWW>0.89) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF89pt300to450": (THWW>0.89) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF89pt450toInf": (THWW>0.89) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF885pt250to300": (THWW>0.885) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF885pt300to450": (THWW>0.885) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF885pt450toInf": (THWW>0.885) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

    "ggF88pt250to300": (THWW>0.88) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt<300)
    "ggF88pt300to450": (THWW>0.88) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>300) & (fj_pt<450)
    "ggF88pt450toInf": (THWW>0.88) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (fj_pt>450)

samples_dir:
    "2018": ../eos/May31_hww_2018
    "2017": ../eos/May31_hww_2017
    "2016": ../eos/May31_hww_2016
    "2016APV": ../eos/May31_hww_2016APV

model_path: ../../weaver-core-dev/experiments_finetuning/v35_30/model.onnx
