events_dict_path: "hists/WithTaggerCut/events_dict.pkl"

years_to_plot:
    - "2018"
    - "2017"
    - "2016"
    - "2016APV"

channels_to_plot:
    - ele
    - mu

regions_to_plot:

    # "2018": met_pt > 20
    # "2017": met_pt > 20
    # "2016": met_pt > 20
    # "2016APV": met_pt > 20

    # "RUN2": met_pt > 20

    Pre-selection: met_pt > 20
    # TopCR: ( (THWW>0.75) & (n_bjets_T>0) )
    # WJets CR: ( (THWW<0.90) & (THWW>0.75) & (n_bjets_T==0) )

    # "VBF": (n_bjets_T==0) & (THWW>0.905) & ( (mjj>1000) & (deta>3.5) ) & (rec_higgs_pt>250)
    # "ggFpt250to350": (n_bjets_T==0) & (THWW>0.93) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<350)
    # "ggFpt350to500": (n_bjets_T==0) & (THWW>0.93) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>350) & (rec_higgs_pt<500)
    # "ggFpt500toInf": (n_bjets_T==0) & (THWW>0.93) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>500)

    # "with": met_pt > 20

samples_to_plot:
    - ggF
    - VBF
    - ttH
    - WH
    - ZH
    - Fake
    # - QCD
    - SingleTop
    - Diboson
    - EWKvjets
    - DYJets
    - WZQQ
    - TTbar
    # - TTbar_allmatched
    # - TTbar_unmatched
    - WJetsLNu
    # - WJetsLNu_unmatched
    # - WJetsLNu_matched
    - Data

vars_to_plot:
    # - THWW
    # - FirstFatjet_pt
    # - SecondFatjet_pt
    # - fj_pt
    # - lep_pt
    # - lep_fj_dr
    # - lep_eta
    # - fj_lsf3
    # - ht
    # - lep_met_mt
    # - met_fj_dphi
    # - met_pt
    # - met_phi
    # - lep_met_mt
    # - NumFatjets
    # - NumOtherJets
    # - rec_W_lnu_m
    # - rec_W_qq_m
    - rec_higgs_m
    # - fj_ParT_mass
    # - fj_mass
    # - lep_isolation_ele_highpt
    # - lep_isolation_ele_lowpt
    # - lep_isolation_mu_highpt
    # - lep_isolation_mu_lowpt
    # - lep_misolation_ele_highpt
    # - lep_misolation_ele_lowpt
    # - lep_misolation_mu_highpt
    # - lep_misolation_mu_lowpt

# outdir: "/Users/fmokhtar/Desktop/AN_2024/SYSTEMATICS/WithTagger/"
# outdir: "/Users/fmokhtar/Desktop/AN_2024/SR"
# outdir: "/Users/fmokhtar/Desktop/AN_2024/TopCR"
outdir: "/Users/fmokhtar/Desktop/AN_2024/lol"

plot_syst_unc: True
plot_Fake_unc: 0.5

add_data: 1
add_soverb: False
logy: 0
legend_ncol: 2
massbin: 20
mult: 5

blind_region: False
# blind_region: [90,160]

# legend_text: ""
# legend_text: "VBF category"
# legend_text: "ggF category pT [250, 350]"
# legend_text: "ggF category pT [350, 500]"
# legend_text: "ggF category pT [500, Inf]"
